Completed prep-css-display.
ChorongShin/prep-1121-code-solutions pull request #7
Opened 2021-11-10 06:43 UTC by ChorongShin

<img width="921" alt="Screen Shot 2021-11-09 at 10 41 38 PM" src="https://user-images.githubusercontent.com/91721272/141063223-1a771d4c-aee1-4757-8396-6255ff22686f.png">

2021-11-10 17:10 UTC, thebearingedge requested changes

2021-11-10 17:10 UTC, thebearingedge commented on prep-css-display/index.html
> +        display: inline;
Oop! There should be one more curly brace here at the end of your last rule set `}` 😄

2021-11-10 17:10 UTC, thebearingedge commented on prep-css-display/index.html
> +        width 100px;
There should be a colon `:` in this declaration.

2021-11-10 22:51 UTC, ChorongShin commented
<img width="921" alt="Screen Shot 2021-11-10 at 2 48 41 PM" src="https://user-images.githubusercontent.com/91721272/141206475-845a69a5-12fe-4fe9-aa42-1a4e1be74b2d.png">

2021-11-11 15:37 UTC, thebearingedge approved these changes

2021-11-12 02:23 UTC, merged