Completed prep-css-flexbox.
ChorongShin/prep-1121-code-solutions pull request #8
Opened 2021-11-12 07:25 UTC by ChorongShin

<img width="1333" alt="Screen Shot 2021-11-11 at 11 18 39 PM" src="https://user-images.githubusercontent.com/91721272/141426954-69d827c3-3700-4093-80f0-ffca14630173.png">
<img width="1329" alt="Screen Shot 2021-11-11 at 11 18 56 PM" src="https://user-images.githubusercontent.com/91721272/141426960-7e9fa3dd-62c3-4102-acd5-0cb3325400cc.png">
<img width="1395" alt="Screen Shot 2021-11-11 at 11 20 02 PM" src="https://user-images.githubusercontent.com/91721272/141426966-8f9f1e9e-7e00-47a9-850e-90feabca6d06.png">
<img width="1398" alt="Screen Shot 2021-11-11 at 11 20 26 PM" src="https://user-images.githubusercontent.com/91721272/141426969-a5fa16bb-aa7d-47b9-9305-d37202ba81f8.png">

2021-11-12 23:59 UTC, thebearingedge requested changes

2021-11-12 23:59 UTC, thebearingedge commented on prep-css-flexbox/align-items.html
> +        flex-basis: calc(100% / 3);
Careful `flex-basis` goes on flex items (children of elements with `display: flex`). You can add another rule set with a selector for `.card-container` and apply the `flex-basis` there.

2021-11-12 23:59 UTC, thebearingedge commented on prep-css-flexbox/flex-wrap.html
> +        flex-basis: calc(100% / 6);
Same here, regarding the application of `flex-basis`, try moving it to your rule set for `.card-container` elements.

2021-11-12 23:59 UTC, thebearingedge commented on prep-css-flexbox/justify-content.html
> +        flex-basis: 25%;
Here as well.

2021-11-13 00:22 UTC, ChorongShin commented
<img width="1413" alt="Screen Shot 2021-11-12 at 4 11 04 PM" src="https://user-images.githubusercontent.com/91721272/141597891-c877d7e4-6795-48b0-bd10-8d99048a6271.png">
<img width="1419" alt="Screen Shot 2021-11-12 at 4 13 57 PM" src="https://user-images.githubusercontent.com/91721272/141597893-de6641ac-7806-46b7-a46c-548abea6f794.png">
<img width="1415" alt="Screen Shot 2021-11-12 at 4 16 19 PM" src="https://user-images.githubusercontent.com/91721272/141597897-6af7cc55-38b9-4593-a326-ecba6c93a688.png">

2021-11-13 16:33 UTC, thebearingedge approved these changes

2021-11-13 17:32 UTC, merged